### ISSUE TITLE
User Stories #1 - List of Upcomming events

### ISSUE THREAD

**Issue by fairytaib** [fairytaib/project_planning_demo#1]
### "As a local resident, I want to see a list of upcoming community events"

**Acceptance criteria**

- [ ] The homepage displays a list uf upcomming community events
- [ ] Each event listing includes the event name, date, time, place and a brief description
- [ ] The list is responsive and looks good on all main device sizes

**Tasks**

- [ ] Add an HTML section on the homepage dedicated to upcoming community events.
- [ ] Style the event list using Bootstrap
- [ ] Add some sample events including event name, date etc.

..
